access-company/testgear

.circleci/config.yml

https://acsmine.tok.access-company.com/redmine/issues/141314

141314_test_using_circle_ci

---

test/gear_config_test.exs
web/controller/config_cache.ex
web/router.ex

https://acsmine.tok.access-company.com/redmine/issues/133935

[133935] add a test for checking that gear configs don't change during web request handling

---

.circleci/config.yml
test/async_job_test.exs

Tests for https://github.com/access-company/antikythera/pull/24
https://acsmine.tok.access-company.com/redmine/issues/147879

[147879] Add tests for :bypass_job_queue option of AsyncJob

---

.circleci/config.yml

https://acsmine.tok.access-company.com/redmine/issues/150737

[150737] Upgrade elixir version for Travis tests

---

test/async_job_test.exs

https://acsmine.tok.access-company.com/redmine/issues/150737

[150737] Declare "@impl" explicitly to suppress warning

---

lib/testgear/test_async_job.ex
test/gear_config_test.exs
test/router_test.exs
web/websocket.ex

https://acsmine.tok.access-company.com/redmine/issues/179080
This commit passes `mix credo --strict`.

[179080] fix credo error (--strict)

---

web/controller/hello.ex

https://acsmine.tok.access-company.com/redmine/issues/185809

Support `sleep` parameter in some APIs

---

web/controller/stress.ex
web/router.ex

https://acsmine.tok.access-company.com/redmine/issues/185809

[185809] Add API for stress test

---

web/controller/stress.ex

https://acsmine.tok.access-company.com/redmine/issues/185809

[185809] Fix to pass dialyzer

---

web/controller/stress.ex

https://acsmine.tok.access-company.com/redmine/issues/185809

[185809] fix warning: variable "loop" is unused

---

.circleci/config.yml
test/async_job_test.exs
test/error_handler_test.exs
test/websocket_test.exs

And make the Erlang version written in `.circleci/config.yml` the same as the version written in `.tool-versions` of Antikythera.
https://acsmine.tok.access-company.com/redmine/issues/207361#note-7

[207361] Suppress error logs displayed during `mix test`

---

test/async_job_test.exs

https://acsmine.tok.access-company.com/redmine/issues/232347#note-23

[232347] Ensure that future time is returned from a mocked function

---

.circleci/config.yml

https://acsmine.tok.access-company.com/redmine/issues/157956#note-68

[157956] CI uses Erlang/OTP 22.3.4.21

---

test/body_parser_test.exs
web/controller/hello.ex
web/router.ex

https://acsmine.tok.access-company.com/redmine/issues/241465

[241465] Add test case for gzipped post body

---

test/content_decoding_test.exs
web/controller/content_decoding.ex
web/router.ex

https://gate.tok.access-company.com/redmine/issues/241420
Test for https://github.com/access-company/antikythera/pull/196

[241420] Test for ContentDecoding plug

---

test/session_test.exs
web/controller/session.ex
web/router.ex

https://acsmine.tok.access-company.com/redmine/issues/241759#note-26

[241759] Add a test for adding set-cookie option by plug

---

test/system_info_exporter_test.exs

https://acsmine.tok.access-company.com/redmine/issues/243004

[243004] Add test for upgradability checker

---

test/websocket_test.exs
web/websocket.ex

https://acsmine.tok.access-company.com/redmine/issues/261457

[261457] Add a test for Registry.Group

---

test/websocket_test.exs
web/websocket.ex

This reverts commit ad4763ecd1844c9cb0c71f9d8b782d98de7d7b2c.
This test is so flaky on our Jenkins server...

Revert "[261457] Add a test for Registry.Group (#32)"

---

test/websocket_test.exs

https://acsmine.tok.access-company.com/redmine/issues/261457

[261457] Update to use new :syn functions

---

test/body_parser_test.exs

https://acsmine.tok.access-company.com/redmine/issues/260138

[260138] CRLF in JSON must be escaped

---

test/timeout_test.exs
web/controller/error.ex
web/router.ex

https://acsmine.tok.access-company.com/redmine/issues/262976#note-11

[262976] Add test for per-API timeout

---

test/error_handler_test.exs
web/controller/error.ex
web/router.ex

https://acsmine.tok.access-company.com/redmine/issues/169945

[169945] Add a test case for raising if a status code, which must not have body, has body

---

test/websocket_test.exs

https://acsmine.tok.access-company.com/redmine/issues/265096

[265096] Add test for handling ping with payload in websocket

---

.circleci/config.yml

https://acsmine.tok.access-company.com/redmine/issues/231052

[231052] Update CircleCI image to OTP 24

---

.markdownlint-cli2.yaml

https://acsmine.tok.access-company.com/redmine/issues/271111

[271111] Introduce markdownlint

---

mix.exs

https://acsmine.tok.access-company.com/redmine/issues/284940

[284940] Fix links to GitHub

---

test/error_handler_test.exs
test/params_validation_test.exs
web/controller/error.ex
web/controller/params_validation.ex
web/router.ex

https://acsmine.tok.access-company.com/redmine/issues/289509

[289509] Test parameter validation plug and its error handling

---

doc/api/openapi_json.json
doc/api/openapi_one.yaml
doc/api/openapi_two.yaml
test/openapi_test.exs
test/test_helper.exs
web/controller/openapi.ex
web/router.ex

https://acsmine.tok.access-company.com/redmine/issues/289510

[289510] Add tests for Antikythera.Test.OpenApiAssertHelper

---

doc/api/openapi_one.yaml
test/openapi_test.exs
web/controller/openapi.ex
web/router.ex

https://acsmine.tok.access-company.com/redmine/issues/289510

[289510] Add more $ref support to OpenApiAssertHelper

---

test/system_info_exporter_test.exs

https://acsmine.tok.access-company.com/redmine/issues/265200

[265200] Add an error before flush in test

---

test/logger_test.exs

https://acsmine.tok.access-company.com/redmine/issues/265200

[265200] Make sure that a new rotated log file is created in the test
